
name: Android CI

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 11
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      # Step 3: Cache Gradle dependencies
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/build.gradle', '**/settings.gradle') }}

          restore-keys: |
            ${{ runner.os }}-gradle

      # Step 4: Build the project
      - name: Build with Gradle
        run: ./gradlew build


      #Step5 : Clean and Build with Gradle
      - name: Clean and Build with Gradle
        run: ./gradlew clean build

      # Step 5: Run unit tests
      - name: Run unit tests
        run: ./gradlew test
